### ISSUE TITLE
Printing Debug Data

### ISSUE THREAD

**Issue by beatles1** [ZackaryH8/tfl-api-wrapper-py#1]
Hi, this module seems great but when using the version from pip it prints a load of debug data with each request. Would it be possible to update the version in PyPI?

**Comment by ZackaryH8** [comment]
Yeah I'll remove or you can make a PR

**Comment by beatles1** [comment]
It doesn't seem to be in the latest code here, only from pip. Not sure how modules get uploaded but I assume you just need to push the latest code?

If I can somehow achieve that via a PR then happy to do so.

**Comment by ZackaryH8** [comment]
Issue resolved by removing a debug print [here](https://github.com/ZackaryH8/tfl-api-wrapper-py/commit/7b4ac7169de4bdefd5e31d9c6b2fc4f8017153a5).

The [PyPi package](https://pypi.org/project/tflwrapper/1.1.6/) has now been updated too.
